export default {
	// ACTIONS
	PROJECTS_RECEIVE_DATA: 'PROJECTS_RECEIVE_DATA',
	PROJECTS_RECEIVE_DATA_ERROR: 'PROJECTS_RECEIVE_DATA_ERROR',
	PROJECT_AWAIT_CREATION_RESPONSE: 'PROJECT_AWAIT_CREATION_RESPONSE',
	PROJECT_RECEIVE_CREATION_RESPONSE: 'PROJECT_RECEIVE_CREATION_RESPONSE',
	PROJECT_EDIT: 'PROJECT_EDIT',
	PROJECT_EDIT_FINISH: 'PROJECT_EDIT_FINISH',
	PROJECT_EDIT_SUBMIT: 'PROJECT_EDIT_SUBMIT',

	// STATES
	PROJECT_EDITING: 'PROJECT_EDITING',
	PROJECT_SUBMITTING: 'PROJECT_SUBMITTING'
};
